# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 990ae67f2b45984f93077921a74d48b9aa06c95410448b96706152843113d77ed9d8fe3ede47e25fd320e7ac9f961584b9b2c29f5c911d117cc1e4c76ca0ea33

test:
  secret_key_base: 9f5935a2b2cc48c3dffe46daba734387f878d99acf53230deac0265e4c4b51b5629f6410f4570e7b8589ad073297bbc884edb82e66fec4a1974caec5af66f328

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
